image Hearts_A = "images/Hearts_A.png"
image Hearts_B = "images/Hearts_B.png"
image Hearts_C = "images/Hearts_C.png"
image Hearts_D = "images/Hearts_D.png"
image Excitement_A = "images/Excitement_A.png"
image Excitement_B = "images/Excitement_B.png"
image Excitement_C = "images/Excitement_C.png"
image Excitement_D = "images/Excitement_D.png"
image Excitement_E = "images/Excitement_E.png"
image Excitement_F = "images/Excitement_F.png"
image Trust_A = "images/Trust_A.png"
image Trust_B = "images/Trust_B.png"
image Trust_C = "images/Trust_C.png"
image Trust_D = "images/Trust_D.png"
image Trust_E = "images/Trust_E.png"
image Trust_F = "images/Trust_F.png"

